version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      APP_PORT: ${APP_PORT:-8080}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME:-appdb}
      DB_SSLMODE: disable
      DB_TIMEZONE: Asia/Jakarta
      JWT_SECRET: ${JWT_SECRET:-supersecretchangeme}
      JWT_EXPIRE_MINUTES: ${JWT_EXPIRE_MINUTES:-60}
      UPLOAD_DIR: /data/uploads
    ports:
      - "8080:8080"
    volumes:
      - uploads:/data/uploads
volumes:
  pgdata:
  uploads:
